# LibMP4FF
# Dreamcast KOS Makefile by PH3NOM 2011

TARGET = libmp4ff.a 

KOS_CFLAGS += -I. -I../../include

OBJS = mp4ff.o mp4atom.o mp4meta.o mp4sample.o mp4util.o \
	 mp4tagupdate.o mp4ff.h mp4ffint.h mp4ff_int_types.h

include $(KOS_BASE)/addons/Makefile.prefab